sudo: false
language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get update -qq
  - yarn install
  - yarn build
  - alias hex="node ./bin/hex.js"
install:
 - export PATH="./bin:$PATH"
after_success:
  - yarn send-coverage
os:
  - linux